"""ppclip builder_remotion — 基于 remotion-video-skill 的 Remotion 项目生成器。

读取 enhanced_timeline.json → 生成 Remotion React 项目文件夹。
适用于 video_type 为 tutorial/visualization 的视频。
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path
from typing import Optional

from .config import BuildConfig


def build(
    project_dir: Path,
    build_cfg: BuildConfig,
    *,
    skill_root: Optional[str] = None,
    verbose: bool = True,
) -> Optional[Path]:
    enhanced_path = project_dir / "enhanced_timeline.json"
    if not enhanced_path.exists():
        if verbose:
            print("  enhanced_timeline.json 不存在，跳过 Remotion")
        return None

    with open(enhanced_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    video_type = data.get("video_type", "clip_splicing")
    if video_type not in ("tutorial", "visualization"):
        if verbose:
            print(f"  video_type={video_type}，跳过 Remotion（仅 tutorial/visualization 生成）")
        return None

    shots = data.get("shots", [])
    if not shots:
        return None

    if verbose:
        print("ppclip build (remotion)")

    remotion_dir = project_dir / "remotion_project"
    remotion_dir.mkdir(parents=True, exist_ok=True)

    project_name = f"ppclip-{project_dir.name}"

    # Copy TTS scripts from skill if available
    if skill_root:
        _copy_skill_scripts(skill_root, remotion_dir)

    # package.json
    _write_package_json(remotion_dir, project_name)

    # remotion.config.ts
    _write_config_ts(remotion_dir)

    # src/audioConfig.ts
    _write_audio_config(remotion_dir, shots, build_cfg.fps)

    # src/Root.tsx
    _write_root_tsx(remotion_dir, build_cfg)

    # src/SceneTemplate.tsx — one reusable component instead of N per-scene files
    _write_scene_template_tsx(remotion_dir, build_cfg)

    # TutorialVideo.tsx — maps over SCENES, drives SceneTemplate
    _write_tutorial_video_tsx(remotion_dir)

    # tsconfig.json
    _write_tsconfig(remotion_dir)

    if verbose:
        print(f"  Remotion 项目已生成: {remotion_dir}")
        print(f"  运行: cd {remotion_dir} && npm install && npm run dev")

    return remotion_dir


def _copy_skill_scripts(skill_root: str, dest: Path) -> None:
    """Copy TTS generation scripts from remotion-video-skill."""
    src_scripts = Path(skill_root) / "scripts"
    if not src_scripts.exists():
        return
    scripts_dest = dest / "scripts"
    scripts_dest.mkdir(exist_ok=True)
    for f in src_scripts.iterdir():
        if f.suffix == ".py":
            shutil.copy2(str(f), str(scripts_dest / f.name))


def _write_package_json(dest: Path, name: str) -> None:
    pkg = {
        "name": name,
        "version": "1.0.0",
        "description": "Generated by ppclip + remotion-video-skill",
        "scripts": {
            "dev": "remotion studio",
            "render": "remotion render TutorialVideo out/video.mp4",
            "audio": "python scripts/generate_audio_edge.py",
        },
        "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "remotion": "^4.0.0",
            "@remotion/three": "^4.0.0",
            "three": "^0.160.0",
            "@react-three/fiber": "^8.15.0",
            "@react-three/drei": "^9.92.0",
        },
        "devDependencies": {
            "@types/react": "^18.2.0",
            "@types/three": "^0.160.0",
            "typescript": "^5.3.0",
        },
    }
    (dest / "package.json").write_text(json.dumps(pkg, indent=2), encoding="utf-8")
    (dest / "src").mkdir(exist_ok=True)
    (dest / "public").mkdir(exist_ok=True)
    (dest / "out").mkdir(exist_ok=True)


def _write_config_ts(dest: Path) -> None:
    (dest / "remotion.config.ts").write_text(
        """import { Config } from "@remotion/cli/config";

Config.setVideoImageFormat("jpeg");
Config.setOverwriteOutput(true);
""",
        encoding="utf-8",
    )


def _write_audio_config(dest: Path, shots: list[dict], fps: int) -> None:
    scenes = []
    for i, s in enumerate(shots):
        dur = s.get("duration", 3.0)
        frames = int(dur * fps)
        sid = f"{i + 1:02d}"
        entry: dict = {
            "id": f"{sid}-scene",
            "title": s.get("subtitle", f"Scene {i + 1}")[:20],
            "durationInFrames": frames,
            "audioFile": f"{sid}-scene.mp3",
        }
        mood = s.get("mood", "")
        role = s.get("clip_role", "")
        if mood:
            entry["mood"] = mood
        if role:
            entry["clipRole"] = role
        scenes.append(entry)

    scenes_ts = json.dumps(scenes, indent=2, ensure_ascii=False)
    content = f"""export interface SceneConfig {{
  id: string;
  title: string;
  durationInFrames: number;
  audioFile: string;
  mood?: string;
  clipRole?: string;
}}

export const SCENES: SceneConfig[] = {scenes_ts};

export function getSceneStart(sceneIndex: number): number {{
  return SCENES.slice(0, sceneIndex).reduce((sum, s) => sum + s.durationInFrames, 0);
}}

export const TOTAL_FRAMES = SCENES.reduce((sum, s) => sum + s.durationInFrames, 0) + 60;

export const FPS = {fps};
"""
    (dest / "src" / "audioConfig.ts").write_text(content, encoding="utf-8")


def _write_root_tsx(dest: Path, build_cfg: BuildConfig) -> None:
    content = f"""import {{ Composition }} from "remotion";
import {{ TutorialVideo }} from "./TutorialVideo";
import {{ TOTAL_FRAMES }} from "./audioConfig";

export const RemotionRoot: React.FC = () => {{
  return (
    <Composition
      id="TutorialVideo"
      component={{TutorialVideo}}
      fps={{30}}
      durationInFrames={{TOTAL_FRAMES}}
      width={{{build_cfg.canvas_width}}}
      height={{{build_cfg.canvas_height}}}
    />
  );
}};
"""
    (dest / "src" / "Root.tsx").write_text(content, encoding="utf-8")


def _write_scene_template_tsx(dest: Path, build_cfg: BuildConfig) -> None:
    """Write reusable SceneTemplate component."""
    content = """import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring, interpolate } from "remotion";

interface SceneTemplateProps {
  title: string;
  mood?: string;
  clipRole?: string;
  sceneIndex: number;
  durationInFrames: number;
}

const MOOD_COLORS: Record<string, string> = {
  "激烈": "#FF6B6B",
  "紧张": "#FF6B6B",
  "平静": "#58C4DD",
  "悲伤": "#58C4DD",
  "搞笑": "#FF8C00",
  "庄严": "#FF8C00",
  "建设": "#58C4DD",
};

export const SceneTemplate: React.FC<SceneTemplateProps> = ({
  title, mood, clipRole, sceneIndex, durationInFrames,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const opacity = interpolate(frame, [0, 12], [0, 1], { extrapolateRight: "clamp" });
  const slideUp = spring({ frame: Math.max(0, frame - 5), fps, config: { damping: 15, stiffness: 80 } });
  const scale = interpolate(frame, [0, durationInFrames], [1.0, 1.03], { extrapolateRight: "clamp" });
  const accentColor = MOOD_COLORS[mood || ""] || "#FF8C00";

  return (
    <AbsoluteFill style={{ backgroundColor: "#0f0f23" }}>
      {mood && (
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 4,
          backgroundColor: accentColor, opacity }} />
      )}
      <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center" }}>
        <div style={{ opacity, transform: `translateY(${(1 - slideUp) * 20}px) scale(${scale})`, textAlign: "center" }}>
          <h1 style={{ color: "#ffffff", fontSize: 52, fontWeight: 700, margin: 0, lineHeight: 1.3, maxWidth: "80vw" }}>{title}</h1>
          {(clipRole || mood) && (
            <div style={{ marginTop: 24, display: "flex", gap: 16, justifyContent: "center" }}>
              {clipRole && <span style={{ color: "rgba(255,255,255,0.5)", fontSize: 14, padding: "4px 12px", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 6 }}>role: {clipRole}</span>}
              {mood && <span style={{ color: "rgba(255,255,255,0.5)", fontSize: 14, padding: "4px 12px", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 6 }}>mood: {mood}</span>}
            </div>
          )}
        </div>
      </div>
      <div style={{ position: "absolute", bottom: 30, left: 40, right: 40, display: "flex", alignItems: "center", gap: 12 }}>
        <span style={{ color: "rgba(255,255,255,0.3)", fontSize: 13 }}>Scene {sceneIndex}</span>
        <div style={{ flex: 1, height: 2, backgroundColor: "rgba(255,255,255,0.1)", borderRadius: 1 }}>
          <div style={{ width: `${Math.min(100, (frame / durationInFrames) * 100)}%`, height: "100%", backgroundColor: "#3498DB", borderRadius: 1, transition: "width 0.1s" }} />
        </div>
      </div>
    </AbsoluteFill>
  );
};
"""
    (dest / "src" / "SceneTemplate.tsx").write_text(content, encoding="utf-8")


def _write_tutorial_video_tsx(dest: Path) -> None:
    """Write TutorialVideo using SceneTemplate — maps over SCENES, one import."""
    content = """import { AbsoluteFill, Audio, Sequence, staticFile, useCurrentFrame } from "remotion";
import { SCENES, getSceneStart, TOTAL_FRAMES } from "./audioConfig";
import { SceneTemplate } from "./SceneTemplate";

const useCurrentSceneIndex = () => {
  const frame = useCurrentFrame();
  let accumulated = 0;
  for (let i = 0; i < SCENES.length; i++) {
    accumulated += SCENES[i].durationInFrames;
    if (frame < accumulated) return i;
  }
  return SCENES.length - 1;
};

export const TutorialVideo: React.FC = () => {
  const sceneIndex = useCurrentSceneIndex();

  return (
    <AbsoluteFill style={{ backgroundColor: "#0f0f23" }}>
      {SCENES.map((scene, idx) => (
        <Sequence key={scene.id} from={getSceneStart(idx)} durationInFrames={scene.durationInFrames}>
          <Audio src={staticFile(`audio/${scene.audioFile}`)} />
        </Sequence>
      ))}
      {SCENES.map((scene, idx) => (
        <Sequence key={`viz-${scene.id}`} from={getSceneStart(idx)} durationInFrames={scene.durationInFrames}>
          <SceneTemplate
            title={scene.title}
            mood={scene.mood}
            clipRole={scene.clipRole}
            sceneIndex={idx + 1}
            durationInFrames={scene.durationInFrames}
          />
        </Sequence>
      ))}
      <div style={{ position: "absolute", bottom: 10, left: 40, right: 40, height: 3, backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 2, zIndex: 100 }}>
        <div style={{ width: `${((sceneIndex + 1) / SCENES.length) * 100}%`, height: "100%", backgroundColor: "#3498DB", borderRadius: 2, transition: "width 0.3s" }} />
      </div>
    </AbsoluteFill>
  );
};
"""
    (dest / "src" / "TutorialVideo.tsx").write_text(content, encoding="utf-8")


def _write_tsconfig(dest: Path) -> None:
    (dest / "tsconfig.json").write_text(
        """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
""",
        encoding="utf-8",
    )
